connection:
  database:
    dw-dev:
      host: 192.168.1.150
      port: 5432
      user: etl_usr
      password: $etl_usr
      dbname: create_dw_dev
    zooguard-dev:
      host: 192.168.1.158
      port: 5432
      user: etl_usr
      password: etl_usr$
      dbname: dev_zooguard